{% set name = "moa-delver" %}
{% set version = "0.1dev1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/wyphan/moa-delver.git

requirements:
  build:
    - python >= 3
    - numpy
    - pandas
    - matplotlib
    - gnuplot
  run:
    - python >= 3
    - numpy
    - pandas
    - matplotlib
    - gnuplot

test:
  # Python imports
  imports:
    - moadelver

about:
  home: https://github.com/wyphan/moa-delver
